# Build
FROM node:18-alpine AS build
WORKDIR /app
COPY overlay/package*.json ./
RUN npm ci
COPY overlay ./
RUN npm run build

# Runtime liviano para servir estático
FROM node:18-alpine
RUN npm i -g serve
WORKDIR /srv
COPY --from=build /app/dist ./dist
ENV PORT=8080
EXPOSE 8080
CMD ["serve","-s","dist","-l","$PORT"]
