FROM node:18-alpine
WORKDIR /app

# Copia el package.json del backend e instala deps
COPY backend/package*.json ./
RUN npm ci --omit=dev

# Copia el código del backend
COPY backend ./

ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "server.js"]
